package com.timthebrick.tinystorage.reference;

public enum GUIs {

	TINY_CHEST, FILTER_CHEST, DRAW, TRASH_CHEST, MICRO_CHEST, WOOL_CHEST, PEACEFUL_CHEST, VACUUM_CHEST, CLAY_CHEST, QUARRY_CHEST, BOOKCASE, STORAGE_BAG

}
