package com.smithsmodding.tinystorage.common.reference;

public enum GUIs {

	TINY_CHEST, FILTER_CHEST, DRAW, TRASH_CHEST, MICRO_CHEST, WOOL_CHEST, PEACEFUL_CHEST, VACUUM_CHEST, CLAY_CHEST, QUARRY_CHEST, BOOKCASE, IMPOSSIBLE_CHEST, FRIEND_SETTER, PERSONAL_SAFE, PASSWORD_SCREEN, STORAGE_BAG

}
